include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true

    # Style rules
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # Pub rules
    sort_pub_dependencies: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

  errors:
    missing_required_param: error
    missing_return: error
