// Mocks generated by Mockito 5.4.6 from annotations
// in doggy_dogs_car_alarm/test/services/alarm_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:doggy_dogs_car_alarm/models/alarm_state.dart' as _i7;
import 'package:doggy_dogs_car_alarm/models/bark_sound.dart' as _i8;
import 'package:doggy_dogs_car_alarm/models/dog.dart' as _i3;
import 'package:doggy_dogs_car_alarm/models/sensor_data.dart' as _i2;
import 'package:doggy_dogs_car_alarm/services/alarm_persistence_service.dart'
    as _i11;
import 'package:doggy_dogs_car_alarm/services/background_monitoring_service.dart'
    as _i9;
import 'package:doggy_dogs_car_alarm/services/bark_audio_service.dart' as _i6;
import 'package:doggy_dogs_car_alarm/services/notification_service.dart'
    as _i10;
import 'package:doggy_dogs_car_alarm/services/sensor_detection_service.dart'
    as _i4;
import 'package:doggy_dogs_car_alarm/services/unlock_code_service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAlarmSensitivity_0 extends _i1.SmartFake
    implements _i2.AlarmSensitivity {
  _FakeAlarmSensitivity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDog_1 extends _i1.SmartFake implements _i3.Dog {
  _FakeDog_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SensorDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSensorDetectionService extends _i1.Mock
    implements _i4.SensorDetectionService {
  MockSensorDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AlarmSensitivity get sensitivity => (super.noSuchMethod(
        Invocation.getter(#sensitivity),
        returnValue: _FakeAlarmSensitivity_0(
          this,
          Invocation.getter(#sensitivity),
        ),
      ) as _i2.AlarmSensitivity);

  @override
  _i5.Stream<_i2.MotionEvent> get motionEvents => (super.noSuchMethod(
        Invocation.getter(#motionEvents),
        returnValue: _i5.Stream<_i2.MotionEvent>.empty(),
      ) as _i5.Stream<_i2.MotionEvent>);

  @override
  bool get isMonitoring => (super.noSuchMethod(
        Invocation.getter(#isMonitoring),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> startMonitoring() => (super.noSuchMethod(
        Invocation.method(
          #startMonitoring,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopMonitoring() => (super.noSuchMethod(
        Invocation.method(
          #stopMonitoring,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> recalibrate() => (super.noSuchMethod(
        Invocation.method(
          #recalibrate,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [BarkAudioService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarkAudioService extends _i1.Mock implements _i6.BarkAudioService {
  MockBarkAudioService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Dog get guardDog => (super.noSuchMethod(
        Invocation.getter(#guardDog),
        returnValue: _FakeDog_1(
          this,
          Invocation.getter(#guardDog),
        ),
      ) as _i3.Dog);

  @override
  bool get isPlaying => (super.noSuchMethod(
        Invocation.getter(#isPlaying),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> startBarking(_i7.AlarmMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #startBarking,
          [mode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopBarking() => (super.noSuchMethod(
        Invocation.method(
          #stopBarking,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> triggerImmediateBark({
    _i8.BarkType? type = _i8.BarkType.aggressive,
    _i8.BarkIntensity? intensity = _i8.BarkIntensity.maximum,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #triggerImmediateBark,
          [],
          {
            #type: type,
            #intensity: intensity,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [BackgroundMonitoringService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackgroundMonitoringService extends _i1.Mock
    implements _i9.BackgroundMonitoringService {
  MockBackgroundMonitoringService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isMonitoring => (super.noSuchMethod(
        Invocation.getter(#isMonitoring),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startMonitoring({
    required _i7.AlarmMode? mode,
    Duration? frequency = const Duration(minutes: 15),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #startMonitoring,
          [],
          {
            #mode: mode,
            #frequency: frequency,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> stopMonitoring() => (super.noSuchMethod(
        Invocation.method(
          #stopMonitoring,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i10.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> showAlarmTriggered({
    required _i2.MotionType? motionType,
    required double? intensity,
    String? dogName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAlarmTriggered,
          [],
          {
            #motionType: motionType,
            #intensity: intensity,
            #dogName: dogName,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> showAlarmActivated({
    required _i7.AlarmMode? mode,
    String? dogName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAlarmActivated,
          [],
          {
            #mode: mode,
            #dogName: dogName,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> showAlarmDeactivated({String? dogName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #showAlarmDeactivated,
          [],
          {#dogName: dogName},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> showDogReminder({
    required String? title,
    required String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDogReminder,
          [],
          {
            #title: title,
            #message: message,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllNotifications,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> areNotificationsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #areNotificationsEnabled,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [AlarmPersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAlarmPersistenceService extends _i1.Mock
    implements _i11.AlarmPersistenceService {
  MockAlarmPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveAlarmState(_i7.AlarmState? state) => (super.noSuchMethod(
        Invocation.method(
          #saveAlarmState,
          [state],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.AlarmState?> loadAlarmState() => (super.noSuchMethod(
        Invocation.method(
          #loadAlarmState,
          [],
        ),
        returnValue: _i5.Future<_i7.AlarmState?>.value(),
      ) as _i5.Future<_i7.AlarmState?>);

  @override
  _i5.Future<void> clearAlarmState() => (super.noSuchMethod(
        Invocation.method(
          #clearAlarmState,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveCurrentDogId(String? dogId) => (super.noSuchMethod(
        Invocation.method(
          #saveCurrentDogId,
          [dogId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> loadCurrentDogId() => (super.noSuchMethod(
        Invocation.method(
          #loadCurrentDogId,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveSensitivity(String? sensitivity) => (super.noSuchMethod(
        Invocation.method(
          #saveSensitivity,
          [sensitivity],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> loadSensitivity() => (super.noSuchMethod(
        Invocation.method(
          #loadSensitivity,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<bool> wasAlarmActive() => (super.noSuchMethod(
        Invocation.method(
          #wasAlarmActive,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<Duration?> getActivationDuration() => (super.noSuchMethod(
        Invocation.method(
          #getActivationDuration,
          [],
        ),
        returnValue: _i5.Future<Duration?>.value(),
      ) as _i5.Future<Duration?>);

  @override
  _i5.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [UnlockCodeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnlockCodeService extends _i1.Mock implements _i12.UnlockCodeService {
  MockUnlockCodeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> hasUnlockCode() => (super.noSuchMethod(
        Invocation.method(
          #hasUnlockCode,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setUnlockCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #setUnlockCode,
          [code],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> validateUnlockCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #validateUnlockCode,
          [code],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> resetToDefault() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefault,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearUnlockCode() => (super.noSuchMethod(
        Invocation.method(
          #clearUnlockCode,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  String getDefaultCode() => (super.noSuchMethod(
        Invocation.method(
          #getDefaultCode,
          [],
        ),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.method(
            #getDefaultCode,
            [],
          ),
        ),
      ) as String);
}
