name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

env:
  FLUTTER_VERSION: '3.35.0'

jobs:
  prepare-release:
    name: Prepare Release Info
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      changelog: ${{ steps.changelog.outputs.changelog }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog generation

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Generate changelog
        id: changelog
        run: |
          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            # First release - get all commits
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            # Get commits since previous tag
            CHANGELOG=$(git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Categorize commits
          FEATURES=$(echo "$CHANGELOG" | grep -i "feat\|feature\|add" || echo "")
          FIXES=$(echo "$CHANGELOG" | grep -i "fix\|bug" || echo "")
          CHANGES=$(echo "$CHANGELOG" | grep -v -i "feat\|feature\|add\|fix\|bug" || echo "")

          # Build changelog content
          {
            echo 'changelog<<EOF'
            echo "## ðŸŽ‰ Release v${{ steps.get_version.outputs.version }}"
            echo ""

            if [ -n "$FEATURES" ]; then
              echo "### âœ¨ New Features"
              echo "$FEATURES"
              echo ""
            fi

            if [ -n "$FIXES" ]; then
              echo "### ðŸ› Bug Fixes"
              echo "$FIXES"
              echo ""
            fi

            if [ -n "$CHANGES" ]; then
              echo "### ðŸ”„ Other Changes"
              echo "$CHANGES"
              echo ""
            fi

            echo "---"
            echo ""
            echo "**Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREV_TAG...v${{ steps.get_version.outputs.version }}"
            echo 'EOF'
          } >> $GITHUB_OUTPUT

  build-android:
    name: Build Android Artifacts
    needs: prepare-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get dependencies
        run: flutter pub get

      - name: Decode keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/keystore.jks

            cat > android/key.properties <<EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEY_PASSWORD
          keyAlias=$KEY_ALIAS
          storeFile=keystore.jks
          EOF
          else
            echo "âš ï¸ Keystore secrets not configured, will build unsigned"
          fi

      - name: Build APK
        run: |
          if [ -f "android/key.properties" ]; then
            flutter build apk --release
          else
            echo "âš ï¸  Building unsigned APK (secrets not configured)"
            flutter build apk --debug
          fi

      - name: Build App Bundle (AAB)
        run: |
          if [ -f "android/key.properties" ]; then
            flutter build appbundle --release
          else
            echo "âš ï¸  Skipping AAB build (requires signing)"
          fi

      - name: Rename artifacts
        run: |
          VERSION="${{ needs.prepare-release.outputs.version }}"

          if [ -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            mv build/app/outputs/flutter-apk/app-release.apk \
               build/app/outputs/flutter-apk/doggy-dogs-android-v${VERSION}.apk
          fi

          if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            mv build/app/outputs/bundle/release/app-release.aab \
               build/app/outputs/bundle/release/doggy-dogs-android-v${VERSION}.aab
          fi

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-${{ needs.prepare-release.outputs.version }}
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
          if-no-files-found: warn
          retention-days: 90

  build-ios:
    name: Build iOS Artifact
    needs: prepare-release
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Fastlane
        run: |
          gem install fastlane
          fastlane --version

      - name: Set up SSH for Match
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
        run: |
          if [ -n "$MATCH_GIT_PRIVATE_KEY" ]; then
            mkdir -p ~/.ssh
            echo "$MATCH_GIT_PRIVATE_KEY" > ~/.ssh/match_deploy_key
            chmod 600 ~/.ssh/match_deploy_key
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            cat > ~/.ssh/config <<EOF
          Host github.com
            HostName github.com
            User git
            IdentityFile ~/.ssh/match_deploy_key
            StrictHostKeyChecking no
          EOF
            echo "âœ… SSH configured"
          else
            echo "âš ï¸ MATCH_GIT_PRIVATE_KEY not configured"
          fi

      - name: Set up provisioning profiles
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: |
          if [ -n "$MATCH_PASSWORD" ] && [ -n "$MATCH_GIT_URL" ]; then
            cd ios
            fastlane match appstore --readonly || {
              echo "âš ï¸  Match failed, will build unsigned"
              exit 0
            }
          else
            echo "âš ï¸ Match secrets not configured"
          fi

      - name: Build IPA
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          if [ -n "$MATCH_PASSWORD" ]; then
            flutter build ipa --release --export-options-plist=ios/ExportOptions.plist || {
              echo "âš ï¸  Signed build failed, skipping iOS"
              exit 0
            }
          else
            echo "âš ï¸  iOS signing not configured, skipping iOS build"
            exit 0
          fi

      - name: Rename IPA
        run: |
          VERSION="${{ needs.prepare-release.outputs.version }}"
          IPA_FILE=$(find build/ios/ipa -name "*.ipa" -type f 2>/dev/null | head -1)

          if [ -n "$IPA_FILE" ] && [ -f "$IPA_FILE" ]; then
            mv "$IPA_FILE" "build/ios/ipa/doggy-dogs-ios-v${VERSION}.ipa"
            echo "âœ… IPA renamed"
          else
            echo "âš ï¸  No IPA file found"
          fi

      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-${{ needs.prepare-release.outputs.version }}
          path: build/ios/ipa/*.ipa
          if-no-files-found: warn
          retention-days: 90

  create-release:
    name: Create GitHub Release
    needs: [prepare-release, build-android, build-ios]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-release-${{ needs.prepare-release.outputs.version }}
          path: ./artifacts/android
        continue-on-error: true

      - name: Download iOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-release-${{ needs.prepare-release.outputs.version }}
          path: ./artifacts/ios
        continue-on-error: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.prepare-release.outputs.version }}
          name: Release v${{ needs.prepare-release.outputs.version }}
          body: ${{ needs.prepare-release.outputs.changelog }}
          draft: false
          prerelease: ${{ contains(needs.prepare-release.outputs.version, 'alpha') || contains(needs.prepare-release.outputs.version, 'beta') || contains(needs.prepare-release.outputs.version, 'rc') }}
          files: |
            ./artifacts/**/*
          fail_on_unmatched_files: false

  update-changelog:
    name: Update CHANGELOG.md
    needs: [prepare-release, create-release]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate full changelog
        run: |
          VERSION="${{ needs.prepare-release.outputs.version }}"
          DATE=$(date +%Y-%m-%d)

          # Get the previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            COMMITS=$(git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          # Create or update CHANGELOG.md
          if [ ! -f CHANGELOG.md ]; then
            cat > CHANGELOG.md <<EOF
          # Changelog

          All notable changes to this project will be documented in this file.

          The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
          and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

          EOF
          fi

          # Prepend new version to CHANGELOG.md
          {
            echo ""
            echo "## [${VERSION}] - ${DATE}"
            echo ""
            echo "$COMMITS"
            echo ""
          } | cat - CHANGELOG.md > CHANGELOG.tmp

          mv CHANGELOG.tmp CHANGELOG.md

      - name: Commit CHANGELOG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for v${{ needs.prepare-release.outputs.version }}" || echo "No changes to commit"
          git push || echo "Nothing to push"

  release-summary:
    name: Release Summary
    needs: [prepare-release, create-release, build-android, build-ios, update-changelog]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Summary
        run: |
          echo "## ðŸŽ‰ Release v${{ needs.prepare-release.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ðŸ“¦ Artifacts Built" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ needs.build-android.result }}" == "success" ]; then
            echo "- âœ… Android APK" >> $GITHUB_STEP_SUMMARY
            echo "- âœ… Android AAB" >> $GITHUB_STEP_SUMMARY
          else
            echo "- âš ï¸  Android build: ${{ needs.build-android.result }}" >> $GITHUB_STEP_SUMMARY
          fi

          if [ "${{ needs.build-ios.result }}" == "success" ]; then
            echo "- âœ… iOS IPA" >> $GITHUB_STEP_SUMMARY
          else
            echo "- âš ï¸  iOS build: ${{ needs.build-ios.result }}" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### ðŸ”— Links" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- [Release Page](https://github.com/${{ github.repository }}/releases/tag/v${{ needs.prepare-release.outputs.version }})" >> $GITHUB_STEP_SUMMARY
          echo "- [Download Artifacts](https://github.com/${{ github.repository }}/releases/download/v${{ needs.prepare-release.outputs.version }}/)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ¤– Generated with [Claude Code](https://claude.com/claude-code)" >> $GITHUB_STEP_SUMMARY
